### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by jwhklk** [li2215890610/taro-study#1]
Failed to compile.
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "base" at 2, attempted to resolve relative to "/Users/***/taro-study-master/.temp"
    at Array.map (<anonymous>)

**Comment by li2215890610** [comment]
你看看你的版本号，或者截图一下，
